# Logstash configuration

http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Log settings
log.level: info
log.format: plain

# Elasticsearch output
xpack.monitoring.enabled: false
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
